services:
  - type: web
    name: flask-selenium-app
    env: python
    runtime: python3
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: CHROMEDRIVER_PATH
        value: /usr/local/bin/chromedriver
      - key: GOOGLE_APPLICATION_CREDENTIALS
        value: /etc/secrets/your_service_account.json
    dockerfile: Dockerfile
