services:
  - type: web
    name: youtube-screenshot-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.6
      - key: GDRIVE_CREDENTIALS
        value: abc.json
