# render.yaml
services:
  - type: web
    name: youtube-screenshot-bot
    env: python
    buildCommand: |
      apt-get update && \
      apt-get install -y chromium chromium-driver && \
      pip install -r requirements.txt
    startCommand: |
      python -u app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.6
      - key: GDRIVE_CREDENTIALS
        value: abc.json
